# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.21

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.21.0/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.21.0/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/ruby/Desktop/Quiz-Game

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/ruby/Desktop/Quiz-Game

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.21.0/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.21.0/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/ruby/Desktop/Quiz-Game/CMakeFiles /Users/ruby/Desktop/Quiz-Game//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/ruby/Desktop/Quiz-Game/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named QuizGame

# Build rule for target.
QuizGame: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 QuizGame
.PHONY : QuizGame

# fast build rule for target.
QuizGame/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QuizGame.dir/build.make CMakeFiles/QuizGame.dir/build
.PHONY : QuizGame/fast

src/AssetMan.o: src/AssetMan.cpp.o
.PHONY : src/AssetMan.o

# target to build an object file
src/AssetMan.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QuizGame.dir/build.make CMakeFiles/QuizGame.dir/src/AssetMan.cpp.o
.PHONY : src/AssetMan.cpp.o

src/AssetMan.i: src/AssetMan.cpp.i
.PHONY : src/AssetMan.i

# target to preprocess a source file
src/AssetMan.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QuizGame.dir/build.make CMakeFiles/QuizGame.dir/src/AssetMan.cpp.i
.PHONY : src/AssetMan.cpp.i

src/AssetMan.s: src/AssetMan.cpp.s
.PHONY : src/AssetMan.s

# target to generate assembly for a file
src/AssetMan.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QuizGame.dir/build.make CMakeFiles/QuizGame.dir/src/AssetMan.cpp.s
.PHONY : src/AssetMan.cpp.s

src/Game.o: src/Game.cpp.o
.PHONY : src/Game.o

# target to build an object file
src/Game.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QuizGame.dir/build.make CMakeFiles/QuizGame.dir/src/Game.cpp.o
.PHONY : src/Game.cpp.o

src/Game.i: src/Game.cpp.i
.PHONY : src/Game.i

# target to preprocess a source file
src/Game.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QuizGame.dir/build.make CMakeFiles/QuizGame.dir/src/Game.cpp.i
.PHONY : src/Game.cpp.i

src/Game.s: src/Game.cpp.s
.PHONY : src/Game.s

# target to generate assembly for a file
src/Game.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QuizGame.dir/build.make CMakeFiles/QuizGame.dir/src/Game.cpp.s
.PHONY : src/Game.cpp.s

src/GameOver.o: src/GameOver.cpp.o
.PHONY : src/GameOver.o

# target to build an object file
src/GameOver.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QuizGame.dir/build.make CMakeFiles/QuizGame.dir/src/GameOver.cpp.o
.PHONY : src/GameOver.cpp.o

src/GameOver.i: src/GameOver.cpp.i
.PHONY : src/GameOver.i

# target to preprocess a source file
src/GameOver.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QuizGame.dir/build.make CMakeFiles/QuizGame.dir/src/GameOver.cpp.i
.PHONY : src/GameOver.cpp.i

src/GameOver.s: src/GameOver.cpp.s
.PHONY : src/GameOver.s

# target to generate assembly for a file
src/GameOver.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QuizGame.dir/build.make CMakeFiles/QuizGame.dir/src/GameOver.cpp.s
.PHONY : src/GameOver.cpp.s

src/GamePlay.o: src/GamePlay.cpp.o
.PHONY : src/GamePlay.o

# target to build an object file
src/GamePlay.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QuizGame.dir/build.make CMakeFiles/QuizGame.dir/src/GamePlay.cpp.o
.PHONY : src/GamePlay.cpp.o

src/GamePlay.i: src/GamePlay.cpp.i
.PHONY : src/GamePlay.i

# target to preprocess a source file
src/GamePlay.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QuizGame.dir/build.make CMakeFiles/QuizGame.dir/src/GamePlay.cpp.i
.PHONY : src/GamePlay.cpp.i

src/GamePlay.s: src/GamePlay.cpp.s
.PHONY : src/GamePlay.s

# target to generate assembly for a file
src/GamePlay.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QuizGame.dir/build.make CMakeFiles/QuizGame.dir/src/GamePlay.cpp.s
.PHONY : src/GamePlay.cpp.s

src/InternalWelcome.o: src/InternalWelcome.cpp.o
.PHONY : src/InternalWelcome.o

# target to build an object file
src/InternalWelcome.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QuizGame.dir/build.make CMakeFiles/QuizGame.dir/src/InternalWelcome.cpp.o
.PHONY : src/InternalWelcome.cpp.o

src/InternalWelcome.i: src/InternalWelcome.cpp.i
.PHONY : src/InternalWelcome.i

# target to preprocess a source file
src/InternalWelcome.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QuizGame.dir/build.make CMakeFiles/QuizGame.dir/src/InternalWelcome.cpp.i
.PHONY : src/InternalWelcome.cpp.i

src/InternalWelcome.s: src/InternalWelcome.cpp.s
.PHONY : src/InternalWelcome.s

# target to generate assembly for a file
src/InternalWelcome.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QuizGame.dir/build.make CMakeFiles/QuizGame.dir/src/InternalWelcome.cpp.s
.PHONY : src/InternalWelcome.cpp.s

src/Introduction.o: src/Introduction.cpp.o
.PHONY : src/Introduction.o

# target to build an object file
src/Introduction.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QuizGame.dir/build.make CMakeFiles/QuizGame.dir/src/Introduction.cpp.o
.PHONY : src/Introduction.cpp.o

src/Introduction.i: src/Introduction.cpp.i
.PHONY : src/Introduction.i

# target to preprocess a source file
src/Introduction.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QuizGame.dir/build.make CMakeFiles/QuizGame.dir/src/Introduction.cpp.i
.PHONY : src/Introduction.cpp.i

src/Introduction.s: src/Introduction.cpp.s
.PHONY : src/Introduction.s

# target to generate assembly for a file
src/Introduction.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QuizGame.dir/build.make CMakeFiles/QuizGame.dir/src/Introduction.cpp.s
.PHONY : src/Introduction.cpp.s

src/Login.o: src/Login.cpp.o
.PHONY : src/Login.o

# target to build an object file
src/Login.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QuizGame.dir/build.make CMakeFiles/QuizGame.dir/src/Login.cpp.o
.PHONY : src/Login.cpp.o

src/Login.i: src/Login.cpp.i
.PHONY : src/Login.i

# target to preprocess a source file
src/Login.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QuizGame.dir/build.make CMakeFiles/QuizGame.dir/src/Login.cpp.i
.PHONY : src/Login.cpp.i

src/Login.s: src/Login.cpp.s
.PHONY : src/Login.s

# target to generate assembly for a file
src/Login.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QuizGame.dir/build.make CMakeFiles/QuizGame.dir/src/Login.cpp.s
.PHONY : src/Login.cpp.s

src/MainMenu.o: src/MainMenu.cpp.o
.PHONY : src/MainMenu.o

# target to build an object file
src/MainMenu.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QuizGame.dir/build.make CMakeFiles/QuizGame.dir/src/MainMenu.cpp.o
.PHONY : src/MainMenu.cpp.o

src/MainMenu.i: src/MainMenu.cpp.i
.PHONY : src/MainMenu.i

# target to preprocess a source file
src/MainMenu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QuizGame.dir/build.make CMakeFiles/QuizGame.dir/src/MainMenu.cpp.i
.PHONY : src/MainMenu.cpp.i

src/MainMenu.s: src/MainMenu.cpp.s
.PHONY : src/MainMenu.s

# target to generate assembly for a file
src/MainMenu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QuizGame.dir/build.make CMakeFiles/QuizGame.dir/src/MainMenu.cpp.s
.PHONY : src/MainMenu.cpp.s

src/MakeWish.o: src/MakeWish.cpp.o
.PHONY : src/MakeWish.o

# target to build an object file
src/MakeWish.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QuizGame.dir/build.make CMakeFiles/QuizGame.dir/src/MakeWish.cpp.o
.PHONY : src/MakeWish.cpp.o

src/MakeWish.i: src/MakeWish.cpp.i
.PHONY : src/MakeWish.i

# target to preprocess a source file
src/MakeWish.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QuizGame.dir/build.make CMakeFiles/QuizGame.dir/src/MakeWish.cpp.i
.PHONY : src/MakeWish.cpp.i

src/MakeWish.s: src/MakeWish.cpp.s
.PHONY : src/MakeWish.s

# target to generate assembly for a file
src/MakeWish.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QuizGame.dir/build.make CMakeFiles/QuizGame.dir/src/MakeWish.cpp.s
.PHONY : src/MakeWish.cpp.s

src/PauseGame.o: src/PauseGame.cpp.o
.PHONY : src/PauseGame.o

# target to build an object file
src/PauseGame.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QuizGame.dir/build.make CMakeFiles/QuizGame.dir/src/PauseGame.cpp.o
.PHONY : src/PauseGame.cpp.o

src/PauseGame.i: src/PauseGame.cpp.i
.PHONY : src/PauseGame.i

# target to preprocess a source file
src/PauseGame.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QuizGame.dir/build.make CMakeFiles/QuizGame.dir/src/PauseGame.cpp.i
.PHONY : src/PauseGame.cpp.i

src/PauseGame.s: src/PauseGame.cpp.s
.PHONY : src/PauseGame.s

# target to generate assembly for a file
src/PauseGame.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QuizGame.dir/build.make CMakeFiles/QuizGame.dir/src/PauseGame.cpp.s
.PHONY : src/PauseGame.cpp.s

src/PlayerInfo.o: src/PlayerInfo.cpp.o
.PHONY : src/PlayerInfo.o

# target to build an object file
src/PlayerInfo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QuizGame.dir/build.make CMakeFiles/QuizGame.dir/src/PlayerInfo.cpp.o
.PHONY : src/PlayerInfo.cpp.o

src/PlayerInfo.i: src/PlayerInfo.cpp.i
.PHONY : src/PlayerInfo.i

# target to preprocess a source file
src/PlayerInfo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QuizGame.dir/build.make CMakeFiles/QuizGame.dir/src/PlayerInfo.cpp.i
.PHONY : src/PlayerInfo.cpp.i

src/PlayerInfo.s: src/PlayerInfo.cpp.s
.PHONY : src/PlayerInfo.s

# target to generate assembly for a file
src/PlayerInfo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QuizGame.dir/build.make CMakeFiles/QuizGame.dir/src/PlayerInfo.cpp.s
.PHONY : src/PlayerInfo.cpp.s

src/Ranking.o: src/Ranking.cpp.o
.PHONY : src/Ranking.o

# target to build an object file
src/Ranking.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QuizGame.dir/build.make CMakeFiles/QuizGame.dir/src/Ranking.cpp.o
.PHONY : src/Ranking.cpp.o

src/Ranking.i: src/Ranking.cpp.i
.PHONY : src/Ranking.i

# target to preprocess a source file
src/Ranking.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QuizGame.dir/build.make CMakeFiles/QuizGame.dir/src/Ranking.cpp.i
.PHONY : src/Ranking.cpp.i

src/Ranking.s: src/Ranking.cpp.s
.PHONY : src/Ranking.s

# target to generate assembly for a file
src/Ranking.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QuizGame.dir/build.make CMakeFiles/QuizGame.dir/src/Ranking.cpp.s
.PHONY : src/Ranking.cpp.s

src/Register.o: src/Register.cpp.o
.PHONY : src/Register.o

# target to build an object file
src/Register.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QuizGame.dir/build.make CMakeFiles/QuizGame.dir/src/Register.cpp.o
.PHONY : src/Register.cpp.o

src/Register.i: src/Register.cpp.i
.PHONY : src/Register.i

# target to preprocess a source file
src/Register.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QuizGame.dir/build.make CMakeFiles/QuizGame.dir/src/Register.cpp.i
.PHONY : src/Register.cpp.i

src/Register.s: src/Register.cpp.s
.PHONY : src/Register.s

# target to generate assembly for a file
src/Register.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QuizGame.dir/build.make CMakeFiles/QuizGame.dir/src/Register.cpp.s
.PHONY : src/Register.cpp.s

src/StateMan.o: src/StateMan.cpp.o
.PHONY : src/StateMan.o

# target to build an object file
src/StateMan.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QuizGame.dir/build.make CMakeFiles/QuizGame.dir/src/StateMan.cpp.o
.PHONY : src/StateMan.cpp.o

src/StateMan.i: src/StateMan.cpp.i
.PHONY : src/StateMan.i

# target to preprocess a source file
src/StateMan.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QuizGame.dir/build.make CMakeFiles/QuizGame.dir/src/StateMan.cpp.i
.PHONY : src/StateMan.cpp.i

src/StateMan.s: src/StateMan.cpp.s
.PHONY : src/StateMan.s

# target to generate assembly for a file
src/StateMan.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QuizGame.dir/build.make CMakeFiles/QuizGame.dir/src/StateMan.cpp.s
.PHONY : src/StateMan.cpp.s

src/Welcome.o: src/Welcome.cpp.o
.PHONY : src/Welcome.o

# target to build an object file
src/Welcome.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QuizGame.dir/build.make CMakeFiles/QuizGame.dir/src/Welcome.cpp.o
.PHONY : src/Welcome.cpp.o

src/Welcome.i: src/Welcome.cpp.i
.PHONY : src/Welcome.i

# target to preprocess a source file
src/Welcome.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QuizGame.dir/build.make CMakeFiles/QuizGame.dir/src/Welcome.cpp.i
.PHONY : src/Welcome.cpp.i

src/Welcome.s: src/Welcome.cpp.s
.PHONY : src/Welcome.s

# target to generate assembly for a file
src/Welcome.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QuizGame.dir/build.make CMakeFiles/QuizGame.dir/src/Welcome.cpp.s
.PHONY : src/Welcome.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QuizGame.dir/build.make CMakeFiles/QuizGame.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QuizGame.dir/build.make CMakeFiles/QuizGame.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QuizGame.dir/build.make CMakeFiles/QuizGame.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... QuizGame"
	@echo "... src/AssetMan.o"
	@echo "... src/AssetMan.i"
	@echo "... src/AssetMan.s"
	@echo "... src/Game.o"
	@echo "... src/Game.i"
	@echo "... src/Game.s"
	@echo "... src/GameOver.o"
	@echo "... src/GameOver.i"
	@echo "... src/GameOver.s"
	@echo "... src/GamePlay.o"
	@echo "... src/GamePlay.i"
	@echo "... src/GamePlay.s"
	@echo "... src/InternalWelcome.o"
	@echo "... src/InternalWelcome.i"
	@echo "... src/InternalWelcome.s"
	@echo "... src/Introduction.o"
	@echo "... src/Introduction.i"
	@echo "... src/Introduction.s"
	@echo "... src/Login.o"
	@echo "... src/Login.i"
	@echo "... src/Login.s"
	@echo "... src/MainMenu.o"
	@echo "... src/MainMenu.i"
	@echo "... src/MainMenu.s"
	@echo "... src/MakeWish.o"
	@echo "... src/MakeWish.i"
	@echo "... src/MakeWish.s"
	@echo "... src/PauseGame.o"
	@echo "... src/PauseGame.i"
	@echo "... src/PauseGame.s"
	@echo "... src/PlayerInfo.o"
	@echo "... src/PlayerInfo.i"
	@echo "... src/PlayerInfo.s"
	@echo "... src/Ranking.o"
	@echo "... src/Ranking.i"
	@echo "... src/Ranking.s"
	@echo "... src/Register.o"
	@echo "... src/Register.i"
	@echo "... src/Register.s"
	@echo "... src/StateMan.o"
	@echo "... src/StateMan.i"
	@echo "... src/StateMan.s"
	@echo "... src/Welcome.o"
	@echo "... src/Welcome.i"
	@echo "... src/Welcome.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

